# - name: Update yum dependency
#   shell: 'yum update -y warn=False'

- name: Disable system firewall
  service: name=firewalld state=stopped

- name: Disable SELINX
  selinux: state=disabled

- name: Setup epel yum source for nginx and tomcat
  yum: name=epel-release state=latest

- name: Ensure tomcat is at the latest version
  yum: name=tomcat state=latest

- name: Get ansible version
  debug: msg="{{ lookup('pipe', 'ansible-playbook --version') }}"

- name: Get current shell
  debug: msg="{{ lookup('env', 'SHELL') }}"

- name: Stop tomcat service
  service: name=tomcat state=stopped 

- name: Backup current WAR home
  shell: 
    'mv {{deploy_to}} {{backup_to}}'

- name: Create WAR home
  file:
    path: "{{deploy_to}}"
    state: directory

- name: "Copy source war to destination" 
  copy:
    src: "roles/deploy/files/{{project_name}}-{{version}}.war"
    dest: "{{deploy_to}}/{{project_name}}.war"
  when: project_name == "todo"

- name: Start tomcat service
  service: name=tomcat state=started

- name: change tomcat home dir owner
  file:
    path: "{{tomcat_home}}"
    state: directory
    owner: tomcat
    group: tomcat
    recurse: yes

- name: Run tomcat health check locally
  shell: "sh roles/deploy/files/health_check.sh {{ site_url }} {{ port }} {{project_name}}"
  delegate_to: localhost
  register: health_status

- debug: msg="{{ health_status.stdout }}"



