- hosts: "{{project_name}}"
  gather_facts: true
  remote_user: vagrant
  become: true
  become_method: sudo
  vars:
    backup_to: "{{deploy_to}}_{{ansible_date_time.epoch}}"
    site_url: "http://172.16.1.102"
    port: "8080"
  roles:
    - deploy
      

     #- debug:
     #    msg="{{backup_to}}"
